/*
   Generated by EX4-TO-MQ4 decompiler V4.0.224.1 []
   Website: http://purebeam.biz
   E-mail : purebeam@gmail.com
*/
#property copyright "Copyright ?2005, Nick Bilak"
#property link      "http://metatrader.50webs.com/"

#property indicator_chart_window

double gda_unused_80[];

int deinit() {
   ObjectDelete("time");
   return (0);
}

int init() {
   return (0);
}

int start() {
   int li_8 = Time[0] + 60 * Period() - TimeCurrent();
   double ld_0 = li_8 / 60.0;
   double ld_1 = ld_0 / Period();
   int li_12 = li_8 % 60;
   li_8 = (li_8 - li_8 % 60) / 60;
   int li_9 = 1;
   if (ld_1 != 1)
      li_9 = Volume[0] / (1 - ld_1);
   int li_10 = Volume[1];
   Comment(li_8 + " minutes " + li_12 + " seconds left to bar end");
   ObjectDelete("time");
   if (ObjectFind("time") != 0) {
      ObjectCreate("time", OBJ_TEXT, 0, Time[0], Close[0] + 0.0005);
      if( li_9 > li_10)
         ObjectSetText("time", "                                         < " + li_8 + ":" + li_12 + " - " + li_10 + " ^ " + li_9 + " >", 8, "Arial", SpringGreen);
      else
         ObjectSetText("time", "                                         < " + li_8 + ":" + li_12 + " - " + li_10 + " _ " + li_9 + " >", 8, "Arial", Goldenrod);
   } else ObjectMove("time", 0, Time[0], Close[0] + 0.0005);
   return (0);
}