/*
   Generated by EX4-TO-MQ4 decompiler ONE FILE V4.0.218.3
   EX4 ID : 04E20A41724C2645BAEB3FDF008C44EC
   Website: http://purebeam.biz
   E-mail : purebeam@gmail.com
*/
#property copyright "Copyright ?2005, MetaQuotes Software Corp."
#property link      "http://www.metaquotes.net"
#property show_inputs

extern int 时间修正 = 0;

int start() {
   string ls_0;
   string ls_8;
   string ls_16;
   string ls_24;
   double ld_32;
   double ld_40;
   double ld_48;
   double ld_unused_56;
   double ld_unused_64;
   int li_72;
   int li_76;
   // Print("start load ");
   int l_file_80 = FileOpen("Record.csv", FILE_CSV|FILE_READ, ",");
   if (l_file_80 < 0) 
   {
      int err=GetLastError();
      Print("error(",err,"): ");
      return (0);
   }
   // Print("load ok");
   ObjectsDeleteAll(0, OBJ_TREND);
   ObjectsDeleteAll(0, OBJ_ARROW);
   while (!FileIsEnding(l_file_80)) {
      ls_8 = FileReadString(l_file_80);
      if (StringLen(ls_8) < 1) return (0);
      li_72 = StrToTime(ls_8);
      li_72 += 60 * (60 * 时间修正);
      ls_0 = FileReadString(l_file_80);
      ld_32 = FileReadNumber(l_file_80);
      ls_24 = FileReadString(l_file_80);
      ld_40 = FileReadNumber(l_file_80);
      ld_unused_56 = FileReadNumber(l_file_80);
      ld_unused_64 = FileReadNumber(l_file_80);
      ls_16 = FileReadString(l_file_80);
      li_76 = StrToTime(ls_16);
      li_76 += 60 * (60 * 时间修正);
      ld_48 = FileReadNumber(l_file_80);
      if (ls_24 == "eurusd") ls_24 = "EURUSD";
      if (ls_24 == "gbpusd") ls_24 = "GBPUSD";
      if (ls_24 == "usdchf") ls_24 = "USDCHF";
      if (ls_24 == "usdjpy") ls_24 = "USDJPY";
      if (ls_24 == "audusd") ls_24 = "AUDUSD";
      if (ls_24 == "usdcad") ls_24 = "USDCAD";
      if (ls_24 == "gld") ls_24 = "GLD";
      if (ls_24 == "eurjpy") ls_24 = "EURJPY";
      if (ls_24 == "nzdusd") ls_24 = "NZDUSD";
      if (ls_24 == "gbpjpy") ls_24 = "GBPJPY";
      if (ls_24 == "gbpchf") ls_24 = "GBPCHF";
      if (ls_24 == "audjpy") ls_24 = "AUDJPY";
      if (ls_24 == "eurchf") ls_24 = "EURCHF";
      if (ls_24 == "gbpcad") ls_24 = "GBPCAD";
      if (ls_24 == "chfjpy") ls_24 = "CHFJPY";
      if (ls_24 == "nzdjpy") ls_24 = "NZDJPY";
      if (ls_24 == "slv") ls_24 = "SLV";
      if (ls_24 == "gbpusd") ls_24 = "GBPUSD";
      if (ls_24 == "usdchf") ls_24 = "USDCHF";
      if (ls_24 == "cadjpy") ls_24 = "CADJPY";
      if (ls_0 == "BUY STOP" || ls_0 == "SELL STOP" || ls_0 == "buy stop" || ls_0 == "sell stop") continue;
      // action, opentime, openprice, lot, closetime, closeprice
      if (Symbol() == ls_24) DrawTrade(ls_0, li_72, ld_40, ld_32, li_76, ld_48);
   }
   FileClose(l_file_80);
   return (0);
}

int GetOPColor(string as_0) {
   string ls_8 = StringSubstr(as_0, 0, 3);
   if (ls_8 == "buy" || ls_8 == "BUY") return (9639167);
   if (ls_8 == "sel" || ls_8 == "SEL") return (16760576);
   return (65535);
}

void DrawTrade(string as_0, int ai_8, double a_price_12, double ad_20, int a_datetime_28, double a_price_32) {
   string l_str_concat_40 = StringConcatenate(TimeToStr(ai_8, TIME_DATE|TIME_MINUTES), " ", as_0, " ", ad_20, " at ", a_price_12);
   string l_str_concat_48 = StringConcatenate(l_str_concat_40, " close at ", a_price_32);
   string l_str_concat_56 = StringConcatenate(TimeToStr(ai_8, TIME_DATE|TIME_MINUTES), " ", as_0, " ", a_price_12, " -> ", a_price_32);
   color l_color_64 = GetOPColor(as_0);
   ObjectCreate(l_str_concat_40, OBJ_ARROW, 0, ai_8, a_price_12);
   ObjectSet(l_str_concat_40, OBJPROP_COLOR, l_color_64);
   ObjectSet(l_str_concat_40, OBJPROP_ARROWCODE, 1);
   ObjectSet(l_str_concat_40, OBJPROP_WIDTH, 1);
   ObjectCreate(l_str_concat_56, OBJ_TREND, 0, ai_8, a_price_12, a_datetime_28, a_price_32);
   ObjectSet(l_str_concat_56, OBJPROP_RAY, FALSE);
   ObjectSet(l_str_concat_56, OBJPROP_COLOR, l_color_64);
   ObjectSet(l_str_concat_56, OBJPROP_STYLE, STYLE_DOT);
   ObjectCreate(l_str_concat_48, OBJ_ARROW, 0, a_datetime_28, a_price_32);
   ObjectSet(l_str_concat_48, OBJPROP_COLOR, l_color_64);
   ObjectSet(l_str_concat_48, OBJPROP_ARROWCODE, 3);
   ObjectSet(l_str_concat_48, OBJPROP_WIDTH, 1);
}